baseURL = 'https://velanora.github.io/'
languageCode = 'en-us'
title = 'Velanora'
theme = 'PaperMod'

[[params.socialIcons]]
name = "Github"
url= "https://github.com/velanora"


[[params.socialIcons]]
name = "Linkedin"
url= "https://www.linkedin.com/in/syeda-areej-e-fatima/"

[params.profileMode]
enabled = true
title = "Syeda Areej E Fatima"
subtitle = "Smiley Face ðŸ˜Š"
imageTitle = "Profile Pic"
imageUrl = "/images/pfp1.jpg"
imageWidth = 250
imageHeight = 250


  [[params.profileMode.buttons]]
  name = "About Me"
  url = "/about"

  [[params.profileMode.buttons]]
  name = "My Dev Diary"
  url = "/posts"

    
  [[menu.main]]
    identifier = "posts"
    name       = "Dev Diary"
    url        = "/posts"


